spring:
  application:
    name  : journalApp
  data:
    mongodb:
      auto-index-creation : true
      uri : mongodb+srv://thisisdivyavinod_db_user:HhX25324zpaVvQ7W@cluster0.g0sxxf8.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thisisdivyavinod@gmail.com
    password: xxx xxx xxx xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true

server:
  port: 8081

logging:
  level:
    com.edigest.jounrnalApp: DEBUG

quotes:
  api:
    key: 8rjYI8LfM0WwYv0P28bGgWGoAaiUF6QbBfnMRyjU

weather:
  api:
    key: fdf9f1383ad287fe13bb5ab01fd43214