spring:
  application:
    name  : journalApp
  data:
    mongodb:
      auto-index-creation : true
      uri : mongodb+srv://thisisdivyavinod_db_user:HhX25324zpaVvQ7W@cluster0.g0sxxf8.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thisisdivyavinod@gmail.com
    password: xxx xxx xxx xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
  kafka:
    bootstrap-servers: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.edigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='BSSVFOEVAALCMRRM' password='cfltduaEotNrQ80s6iSUJug4ytOQJWzELEhsrQE3JSLYYsxBSVEsz72DfVkyEqTA';
      session:
        timeout:
          ms: 45000
      client:
        id: ccloud-springboot-client-130c9f18-6552-46d9-ae2b-a999e44ef380

server:
  port: 8081

logging:
  level:
    com.edigest.jounrnalApp: DEBUG

quotes:
  api:
    key: 8rjYI8LfM0WwYv0P28bGgWGoAaiUF6QbBfnMRyjU

weather:
  api:
    key: fdf9f1383ad287fe13bb5ab01fd43214